package com.xts.shop.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xts.shop.model.bean.HistorySearchBean;

import com.xts.shop.db.HistorySearchBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historySearchBeanDaoConfig;

    private final HistorySearchBeanDao historySearchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historySearchBeanDaoConfig = daoConfigMap.get(HistorySearchBeanDao.class).clone();
        historySearchBeanDaoConfig.initIdentityScope(type);

        historySearchBeanDao = new HistorySearchBeanDao(historySearchBeanDaoConfig, this);

        registerDao(HistorySearchBean.class, historySearchBeanDao);
    }
    
    public void clear() {
        historySearchBeanDaoConfig.clearIdentityScope();
    }

    public HistorySearchBeanDao getHistorySearchBeanDao() {
        return historySearchBeanDao;
    }

}
